name: Build Hev-Socks5-Tunnel Android

on:
  workflow_dispatch: # 显式启用手动触发

jobs:
  build-android:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [arm, arm64, x86, x86_64]

    steps:
    - name: Clone Target Repository
      uses: actions/checkout@v4
      with:
        repository: 'heiher/hev-socks5-tunnel'
        ref: 'main'
        submodules: recursive

    - name: Setup Go Environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25c
        add-to-path: true

    - name: Build Binary
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        mkdir -p output
        
        if [ "${{ matrix.arch }}" = "arm" ]; then
          export GOARCH=arm
          export GOARM=7
          export ANDROID_ARCH=arm
        elif [ "${{ matrix.arch }}" = "arm64" ]; then
          export GOARCH=arm64
          export ANDROID_ARCH=arm64
        elif [ "${{ matrix.arch }}" = "x86" ]; then
          export GOARCH=386
          export ANDROID_ARCH=x86
        elif [ "${{ matrix.arch }}" = "x86_64" ]; then
          export GOARCH=amd64
          export ANDROID_ARCH=x86_64
        fi
        
        export GOOS=android
        export CGO_ENABLED=1
        
        CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/${ANDROID_ARCH}-linux-android29-clang
        if [ "${{ matrix.arch }}" = "arm" ]; then
          CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi29-clang
        fi
        
        CC=$CC go build -ldflags "-w -s" -o output/hev-socks5-tunnel-android-${{ matrix.arch }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hev-socks5-tunnel-android-${{ matrix.arch }}
        path: output/hev-socks5-tunnel-android-${{ matrix.arch }}
