name: Build hev-socks5-tunnel ARM64 Binary
run-name: Build Termux AARCH64 Bin

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 源码编译分支
        default: main
        required: false

jobs:
  build-aarch64:
    runs-on: ubuntu-latest
    steps:
      - name: 安装编译依赖与交叉编译器
        run: |
          sudo apt update
          sudo apt install -y git make autoconf automake libtool gcc aarch64-linux-gnu-gcc

      - name: 克隆源码并拉取全部子模块
        run: |
          git clone --recursive https://github.com/heiher/hev-socks5-tunnel.git src
          cd src
          git checkout ${{ github.event.inputs.ref || 'main' }}

      - name: 交叉编译 ARM64(aarch64) 二进制程序
        run: |
          cd src
          ./autogen.sh
          mkdir build-aarch64 && cd build-aarch64
          # 指定交叉编译主机架构 aarch64-linux-gnu
          ../configure --host=aarch64-linux-gnu
          make -j$(nproc)

      - name: 整理编译成品
        run: |
          mkdir output
          cp src/build-aarch64/.libs/hev-socks5-tunnel output/hev-socks5-tunnel-aarch64

      - name: 上传二进制文件
        uses: actions/upload-artifact@v4
        with:
          name: hev-socks5-tunnel-termux-arm64
          path: output/
          
